version: "3.7"

services:
  gogs:
    image: diamol/gogs
    ports:
      - "3000:3000"
    networks:
      - infrastructure
    # 내가 추가한 부분. 이거 없어서 에러남.
    environment:
      - USER=git
      - USERNAME=git
    command: ./gogs web

  registry.local:
    image: diamol/registry
    ports:
      - "5000:5000"
    networks:
      - infrastructure

  jenkins:
    image: diamol/jenkins
    # image: jenkins/jenkins:jdk11
    ports:
      - "8080:8080"
    networks:
      - infrastructure

networks:
  infrastructure:
    name: build-infrastructure
